# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hello_world.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client

if typing.TYPE_CHECKING:
    import grpclib.server

from . import hello_world_pb2


class GreeterBase(abc.ABC):
    @abc.abstractmethod
    async def SayHello(
        self,
        stream: "grpclib.server.Stream[hello_world_pb2.HelloRequest, hello_world_pb2.HelloReply]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/helloworld.Greeter/SayHello": grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                hello_world_pb2.HelloRequest,
                hello_world_pb2.HelloReply,
            ),
        }


class GreeterStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            "/helloworld.Greeter/SayHello",
            hello_world_pb2.HelloRequest,
            hello_world_pb2.HelloReply,
        )
