import asyncio

from grpclib.utils import graceful_exit
from grpclib.server import Server
from grpclib.reflection.service import ServerReflection

# generated by grpcio-tools
from .protocols.hello_world_pb2 import HelloReply
from .protocols.hello_world_grpc import GreeterBase


class Greeter(GreeterBase):
    async def SayHello(self, stream):
        request = await stream.recv_message()
        message = f"Hello, {request.name}!"
        await stream.send_message(HelloReply(message=message))


async def main(*, host="127.0.0.1", port=50051):
    services = [Greeter()]
    services = ServerReflection.extend(services)
    server = Server(services)

    with graceful_exit([server]):
        await server.start(host, port)
        print(f"Serving on {host}:{port}")
        await server.wait_closed()


if __name__ == "__main__":
    asyncio.run(main())
